# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_archived_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='published_date',
            new_name='challenge_start',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='archived_date',
            new_name='challenge_stop',
        ),
    ]
